version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
    environment: 
      # NOTE: MYSQL_HOST/DATABASE/USER/PASSWORD should match values in db container
      MYSQL_URL: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    command: sleep infinity
    network_mode: service:db

  db:
    container_name: ${DB_HOST}
    image: mysql:8.3
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      # NOTE: MYSQL_HOST/DATABASE/USER/PASSWORD should match values in app container
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MySQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: redis
    restart: unless-stopped

volumes:
  mysql-data:
