// <auto-generated />
using System;
using LRV.Regatta.Buero.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LRV.Regatta.Buero.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250410074948_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LRV.Regatta.Buero.Models.FinishObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FinishObjects");
                });

            modelBuilder.Entity("LRV.Regatta.Buero.Models.RegistrationObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChairMan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position1")
                        .HasColumnType("text");

                    b.Property<string>("Position2")
                        .HasColumnType("text");

                    b.Property<string>("Position3")
                        .HasColumnType("text");

                    b.Property<string>("Position4")
                        .HasColumnType("text");

                    b.Property<string>("Position5")
                        .HasColumnType("text");

                    b.Property<string>("Position6")
                        .HasColumnType("text");

                    b.Property<string>("Position7")
                        .HasColumnType("text");

                    b.Property<string>("Position8")
                        .HasColumnType("text");

                    b.Property<string>("PositionCox")
                        .HasColumnType("text");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StartNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RegistrationObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
