// <auto-generated />
using System;
using LRV.Regatta.Buero.Models;
using LRV.Regatta.Buero.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LRV.Regatta.Buero.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250422101700_UpdatedFinishObject")]
    partial class UpdatedFinishObject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LRV.Regatta.Buero.Models.FinishObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SecondPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FinishObjects");
                });

            modelBuilder.Entity("LRV.Regatta.Buero.Models.RegistrationObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChairMan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position1")
                        .HasColumnType("longtext");

                    b.Property<string>("Position2")
                        .HasColumnType("longtext");

                    b.Property<string>("Position3")
                        .HasColumnType("longtext");

                    b.Property<string>("Position4")
                        .HasColumnType("longtext");

                    b.Property<string>("Position5")
                        .HasColumnType("longtext");

                    b.Property<string>("Position6")
                        .HasColumnType("longtext");

                    b.Property<string>("Position7")
                        .HasColumnType("longtext");

                    b.Property<string>("Position8")
                        .HasColumnType("longtext");

                    b.Property<string>("PositionCox")
                        .HasColumnType("longtext");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StartNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RegistrationObjects");
                });

            modelBuilder.Entity("LRV.Regatta.Buero.Models.TeamObject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Kurzform")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lettern")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TeamObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
