services:

  regattadb:
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - regattadb
  
  redis:
    image: redis
    ports:
      - 6379:6379

  redisInsights:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    depends_on:
      - redis
    environment:
      - RI_REDIS_HOST=redis