services:
  lrv.regatta.buero:
    image: ${DOCKER_REGISTRY-}lrvregattabuero
    build:
      context: .
      dockerfile: LRV.Regatta.Buero/Dockerfile

  regattadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: regatta_database
      MYSQL_USER: regatta
      MYSQL_PASSWORD: regatta
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: regattadb
      PMA_USER: regatta
      PMA_PASSWORD: regatta
    ports:
      - "80:80"
    depends_on:
      - regattadb