services:
  backend:
    build: LRV.Regatta.Buero
    restart: always
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8000
      - MARIADB_PASSWORD=my_cool_secret
    networks: 
      - regatta

  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks: 
      - regatta
    environment:
      - MARIADB_USER=example-user 
      - MARIADB_PASSWORD=my_cool_secret
      - MARIADB_DATABASE=exmple-database
      - MARIADB_ROOT_PASSWORD=my-secret-pw 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - regatta

  proxy:
    build: Buero.Frontend
    ports:
      - 80:80
    depends_on: 
      - backend
    networks: 
      - regatta
      - proxy-tier
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-tier
      - traefik.http.routers.regatta-buero.entrypoints=websecure
      - traefik.http.routers.regatta-buero.rule=Host(`buero.luebeckregatta.de`)
      - traefik.http.routers.regatta-buero.tls=true
      - traefik.http.routers.regatta-buero.tls.certresolver=letsencrypt
  
  redis:
    image: redis:alpine
    restart: always
    networks: 
      - regatta

volumes:
  db-data:

networks:
  regatta:
  proxy-tier:
    external: true